// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jgtssrlzikikvnaxilpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndHNzcmx6aWtpa3ZuYXhpbHBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk1MjA3NTAsImV4cCI6MjA5NTA5Njc1MH0.UHvG4wjjlkdbGkel6bsfj0s65Nk4alrHe-VgXpOxYUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);