
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bydxwuppwpbybrgzrzey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5ZHh3dXBwd3BieWJyZ3pyemV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkxMDEwNTEsImV4cCI6MjA5NDY3NzA1MX0._DEeZjcVuO9urXTLWFU2IaUR84hWKYYCqhV80BYhIII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
